#!/bin/sh

years_list=$(
start_year=2012
current_year=$(date +%Y)
year=$start_year
while [ $year -le $current_year ]; do
    printf "$year\n"
    year=$((year + 1))
done
)

selected_year=$(echo $years_list | tr ' ' '\n' | fzf --reverse --prompt="Year:")
echo "Selected Year: $selected_year"

schedule_xml=$(curl -s -L --compressed https://fosdem.org/$selected_year/schedule/xml)

selected_track=$(echo $schedule_xml | xmlstarlet sel -t -v "//track" | uniq | fzf --reverse --prompt="Track:")
echo "Selected track: $selected_track"

selected_talk=$(echo $schedule_xml | xmlstarlet sel -t -m "//event[track=\"$selected_track\"]" -v title -n | fzf --reverse --prompt="Talk:")
echo "Selected talk: $selected_talk"

video_link=$(echo $schedule_xml | xmlstarlet sel -t -v "//event[title=\"$selected_talk\"]/links/link[1]/@href")
echo "Video link: $video_link"

mpv $video_link

